[package]
name = "ngt"
version = "0.1.1"
authors = ["Romain Leroux <romain@leroux.dev>"]
edition = "2018"
description = "Rust wrappers for NGT nearest neighbor search."
repository = "https://github.com/lerouxrgd/ngt-rs"
keywords = ["ngt", "knn", "ann", "optimization"]
categories = ["science"]
license = "Apache-2.0"
readme = "README.md"

[dependencies]
ngt-sys = { path = "ngt-sys", version = "1.11.4" }
num_enum = "0.5"
scopeguard = "1.1"

[dev-dependencies]
rayon = "1.3"
tempfile = "3.1"

[features]
shared_mem = ["ngt-sys/shared_mem"]
large_data = ["ngt-sys/large_data"]
